# -------- BUILD STAGE --------
FROM node:22-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json turbo.json ./
COPY apps/frontend/package.json apps/frontend/
COPY packages/*/package.json packages/*/

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build --workspace=frontend

# -------- NGINX STAGE --------
FROM nginx:alpine
COPY --from=builder /app/apps/frontend/dist /usr/share/nginx/html
